name: Unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Collect MOD files
      run: |
        mkdir mod
        wget https://standard-email.s3-eu-west-1.amazonaws.com/glia__dbbs_mod_collection__NMDA__granule_cell_deterministic.mod -o tests/mod/NMDA.mod
        wget https://standard-email.s3-eu-west-1.amazonaws.com/glia__dbbs_mod_collection__Kca1_1__0.mod -o tests/mod/Kca1_1.mod
    - name: Run unittests
      run: |
        coverage run -m unittest discover -s tests
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
